name: Sync Worker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天自动执行一次，可以根据需要调整

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download latest worker.zip
        run: |
          curl -L -o worker.zip https://github.com/bia-pain-bache/BPB-Worker-Panel/releases/download/v3.2.3/worker.zip

      - name: Unzip worker.zip
        run: |
          rm -rf worker
          unzip -o worker.zip -d worker

      - name: Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add worker
          git commit -m "Update worker files from release" || echo "No changes to commit"
          git push
